import db from '../../config/db.js';

// Get today's available daily foods and standard foods
export const getTodaysMenu = async () => {
    const today = new Date().toISOString().slice(0, 10); // Get YYYY-MM-DD format

    // CORRECTED QUERY: This now correctly joins and groups the component names for each meal
    const [dailyFoods] = await db.execute(
        `SELECT 
            df.d_id, df.d_name, df.meal_type, df.meal_price, df.c_id,
            GROUP_CONCAT(dfc.dfc_name SEPARATOR ', ') as component_names
         FROM 
            daily_food df
         LEFT JOIN 
            daily_food_daily_component dfdc ON df.d_id = dfdc.d_id
         LEFT JOIN 
            daily_food_component dfc ON dfdc.dfc_id = dfc.dfc_id
         WHERE 
            df.meal_date >= ?
         GROUP BY
            df.d_id
         ORDER BY 
            df.meal_date ASC`,
        [today]
    );

    // Fetch standard, available food items that haven't expired
    const [standardFoods] = await db.execute(
        `SELECT f_id, f_name, price, c_id FROM food WHERE stock > 0 AND expire_date >= ?`,
        [today]
    );

    return { dailyFoods, standardFoods };
};

// ... (The rest of your createOrder function remains the same)
export const createOrder = async (customerId, cartItems) => {
    const connection = await db.getConnection();
    try {
        await connection.beginTransaction();

        let totalAmount = 0;
        // First, calculate the total amount of the order
        for (const item of cartItems) {
            const price = item.d_id ? item.meal_price : item.price;
            totalAmount += price * item.quantity;
        }

        // Create a new cart entry for this specific order
        // NOTE: Your schema has one cart per order.
        const [cartResult] = await connection.execute(
            'INSERT INTO cart (cus_id, total_amount) VALUES (?, ?)',
            [customerId, totalAmount]
        );

        // Since cart_id is a varchar set by a trigger, we retrieve it like this
        const [[{ cart_id }]] = await connection.execute(
            'SELECT cart_id FROM cart WHERE cus_id = ? ORDER BY cart_id DESC LIMIT 1',
            [customerId]
        );

        // Now, log the items that were in the cart for this order
        for (const item of cartItems) {
            if (item.d_id) { // This is a daily food item
                await connection.execute(
                    'UPDATE cart SET d_id = ?, item_count = ? WHERE cart_id = ?',
                    [item.d_id, item.quantity, cart_id]
                );
            } else if (item.f_id) { // This is a standard food item
                await connection.execute(
                    'UPDATE cart SET f_id = ?, item_count = ? WHERE cart_id = ?',
                    [item.f_id, item.quantity, cart_id]
                );
            }
        }

        // Finally, create the order record linked to the cart we just made
        const [orderResult] = await connection.execute(
            'INSERT INTO orders (total_amount, cart_id) VALUES (?, ?)',
            [totalAmount, cart_id]
        );

        // Retrieve the order_id that was generated by the trigger
        const [[{ order_id }]] = await connection.execute(
            'SELECT order_id FROM orders WHERE cart_id = ? ORDER BY order_id DESC LIMIT 1',
            [cart_id]
        );

        await connection.commit();
        
        // Return the unique order ID (token) and the total amount to the frontend
        return { orderId: order_id, totalAmount: totalAmount };

    } catch (error) {
        await connection.rollback();
        console.error("Error in createOrder model:", error);
        throw error;
    } finally {
        connection.release();
    }
};
